#! /bin/dash

usage () {
	echo 'Usage: generateMakefile.sh name [directory]
where:
 	name is the name of the program
 	directory is the source directory'
}
find_dep () {
		if [ ! -f $1 ] || [ ! -s $1 ]; then
			return;
		fi
		DEPS="$DEPS $(grep '#include' "$1" | sed 's/#include "//;s/"//' | tr '\n' ' ')"
		NBRDEPS=$(echo $DEPS | wc -w)
		COMPT=0
		while [ $COMPT -ne $NBRDEPS ];do
			COMPT=$(($COMPT+1))
			TEMPDEPS=$(echo $DEPS | cut -d ' ' -f $COMPT)
			if [ "$TEMPDEPS" = "$1" ]; then
				return;
			fi
			find_dep $TEMPDEPS
		done
}
# Test nombre d'argument et savoir si l'argument 2 est un dossier
if [ $# -ne 2 ]; then
	echo 'Incorrect number arguments' >&2
	usage >&2
	exit 1
fi
if [ ! -d $2 ]; then
	echo 'Error :' $2 'doesn’t exist or isn’t a directory' >&2
	usage >&2
	exit 2
fi

PROGRAM="$1"
ROOTDIR="$2"

cd "$ROOTDIR"


# parcourir fichier c un par un et voir indépendance
CFILES=$(ls *.c)
NBRCFILES=$(echo "$CFILES" | wc -w)
COMPTEUR=0
DEPS=""

if [ "$NBRCFILES" -eq 0 ]; then
	echo 'Error : no .c files' >&2
	usage >&2
	exit 3
fi


while [ "$COMPTEUR" -ne "$NBRCFILES" ]; do
	COMPTEUR=$(($COMPTEUR+1))
	TEMP=$(echo $CFILES | cut -d ' ' -f "$COMPTEUR")
	find_dep $TEMP
done
DEPS=$(echo $DEPS | tr ' ' '\n' | uniq)
echo $DEPS

# ---------------------- Génération du Makefile ----------------#

touch Makefile

echo '# Generated by generateMakefile.sh' > Makefile
echo 'CC=gcc' >> Makefile
echo 'CFLAG=' $CFLAG >> Makefile
echo 'LDFLAG=' $LDFLAG >> Makefile
echo 'TARGET='$PROGRAM >> Makefile
echo '\n' >> Makefile
echo 'all: $(TARGET) \n' >> Makefile

COMPTEUR=0
TEMPO=""
while [ "$COMPTEUR" -ne "$NBRCFILES" ]; do
	COMPTEUR=$(($COMPTEUR+1))
	TEMP=$(echo $CFILES | cut -d ' ' -f "$COMPTEUR" | sed "s/\.c//g" )
	echo $TEMP'.o: ' $DEPS  >> Makefile
	echo '	$(CC)' $CFLAGS '-c -o' $TEMP'.o' $DEPS >> Makefile
	TEMPO="$TEMPO $TEMP.o"
done

echo $PROGRAM': ' $TEMPO $DEPS >> Makefile
echo '	$(CC)' $CFLAGS '-c -o '$TEMPO $PROGRAM >> Makefile
echo 'clean: \n' >> Makefile
echo '	rm -f *.o' >> Makefile
echo 'mrproper: \n' >> Makefile

exit 0